services:
  # Backend Golang Service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

  # Frontend React Service (using pnpm)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_GO_APP_API_URL: ${VITE_GO_APP_API_URL}
    depends_on:
      - server
